@extends('layouts.pdf')

@section('content')
<div style="font-family: 'Times-Roman', serif; font-size: 12px; line-height: 1.4;">
    <!-- Header with Logo -->
    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; border-bottom: 2px solid #000; padding-bottom: 15px;">
        <div style="display: flex; align-items: center;">
            @if($company && $company->logo)
                <img src="{{ public_path('storage/' . $company->logo) }}" alt="Company Logo" style="height: 60px; margin-right: 15px;">
            @endif
            <div>
                <h2 style="margin: 0; font-size: 18px; font-weight: bold; color: #333;">
                    {{ $company ? $company->name : 'School Management System' }}
                </h2>
                @if($branch)
                    <p style="margin: 5px 0; font-size: 14px; color: #666;">
                        {{ $branch->name }}
                    </p>
                @endif
            </div>
        </div>
        <div style="text-align: right;">
            <h3 style="margin: 0; font-size: 16px; font-weight: bold; color: #333;">
                Student Transfers Report
            </h3>
            <p style="margin: 5px 0; font-size: 10px; color: #666;">
                Generated on: {{ now()->format('F d, Y H:i') }}
            </p>
        </div>
    </div>

    <!-- Applied Filters -->
    <div style="margin-bottom: 20px; background-color: #f8f9fa; padding: 10px; border-radius: 5px;">
        <h4 style="margin: 0 0 10px 0; font-size: 12px; color: #333;">Applied Filters:</h4>
        <div style="font-size: 10px; color: #666;">
            @if($request->transfer_type)
                <strong>Transfer Type:</strong> {{ ucwords(str_replace('_', ' ', $request->transfer_type)) }}<br>
            @endif
            @if($request->status)
                <strong>Status:</strong> {{ ucfirst($request->status) }}<br>
            @endif
            @if($request->date_from)
                <strong>From Date:</strong> {{ $request->date_from }}<br>
            @endif
            @if($request->date_to)
                <strong>To Date:</strong> {{ $request->date_to }}<br>
            @endif
            <strong>Total Records:</strong> {{ $transfers->count() }}<br>
            <strong>Generated By:</strong> {{ auth()->check() ? auth()->user()->name : 'System' }}
        </div>
    </div>

    <!-- Transfers Table -->
    <table style="width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 9px;">
        <thead>
            <tr style="background-color: #f8f9fa;">
                <th style="border: 1px solid #ddd; padding: 8px; text-align: center; font-weight: bold; width: 5%;">#</th>
                <th style="border: 1px solid #ddd; padding: 8px; text-align: left; font-weight: bold; width: 10%;">Transfer ID</th>
                <th style="border: 1px solid #ddd; padding: 8px; text-align: left; font-weight: bold; width: 15%;">Student Name</th>
                <th style="border: 1px solid #ddd; padding: 8px; text-align: left; font-weight: bold; width: 10%;">Admission No.</th>
                <th style="border: 1px solid #ddd; padding: 8px; text-align: left; font-weight: bold; width: 8%;">Class</th>
                <th style="border: 1px solid #ddd; padding: 8px; text-align: left; font-weight: bold; width: 10%;">Transfer Type</th>
                <th style="border: 1px solid #ddd; padding: 8px; text-align: left; font-weight: bold; width: 12%;">From School</th>
                <th style="border: 1px solid #ddd; padding: 8px; text-align: left; font-weight: bold; width: 12%;">To School</th>
                <th style="border: 1px solid #ddd; padding: 8px; text-align: left; font-weight: bold; width: 9%;">Transfer Date</th>
                <th style="border: 1px solid #ddd; padding: 8px; text-align: left; font-weight: bold; width: 7%;">Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($transfers as $index => $transfer)
            <tr>
                <td style="border: 1px solid #ddd; padding: 6px; text-align: center;">{{ $index + 1 }}</td>
                <td style="border: 1px solid #ddd; padding: 6px;">TRF-{{ str_pad($transfer->id, 6, '0', STR_PAD_LEFT) }}</td>
                <td style="border: 1px solid #ddd; padding: 6px;">
                    {{ $transfer->student ? $transfer->student->first_name . ' ' . $transfer->student->last_name : 'N/A' }}
                </td>
                <td style="border: 1px solid #ddd; padding: 6px;">
                    {{ $transfer->student ? $transfer->student->admission_number : 'N/A' }}
                </td>
                <td style="border: 1px solid #ddd; padding: 6px;">
                    {{ $transfer->student && $transfer->student->class ? $transfer->student->class->name : 'N/A' }}
                </td>
                <td style="border: 1px solid #ddd; padding: 6px;">
                    {{ ucwords(str_replace('_', ' ', $transfer->transfer_type)) }}
                </td>
                <td style="border: 1px solid #ddd; padding: 6px;">
                    {{ $transfer->previous_school ?? 'N/A' }}
                </td>
                <td style="border: 1px solid #ddd; padding: 6px;">
                    {{ $transfer->new_school ?? 'N/A' }}
                </td>
                <td style="border: 1px solid #ddd; padding: 6px;">
                    {{ $transfer->transfer_date ? $transfer->transfer_date->format('M d, Y') : 'N/A' }}
                </td>
                <td style="border: 1px solid #ddd; padding: 6px;">
                    {{ ucfirst($transfer->status) }}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <!-- Footer -->
    <div style="margin-top: 30px; text-align: center; font-size: 10px; color: #666; border-top: 1px solid #ddd; padding-top: 15px;">
        <p style="margin: 0;">
            This report was generated from the School Management System<br>
            <strong>Confidential - For Internal Use Only</strong>
        </p>
    </div>
</div>
@endsection